version: '2.2'
services:
  mysql:
    image: mysql:5.7
    container_name: docker_tool_mysql
    hostname: docker-tool-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "asdfQWER"
      MYSQL_USER: 'user_1'
      MYSQL_PASS: 'asdfQWER'
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
